anno_color<-list(
  TIME.POINT.2=c("Pre"="darkorange2",
                 "2 week"  ="mediumpurple",
                 "2 month"="royalblue2",
                 "6 month"="darkgreen"),
  
  SUPER.PATHWAY=c("Amino Acid"="deepskyblue2",
                  "Carbohydrate" ="darkorchid1",
                  "Cofactors and Vitamins"  ="coral",
                  "Energy"="darkslategrey",
                  "Lipid"="gold",
                  "Nucleotide"="firebrick2",
                  "Peptide"="lightblue",
                  "Xenobiotics"="olivedrab2"),
  
  AA_group=c("*C. difficile* Auxotrophy"="gold",
             "Stickland Substrate"="darkorchid1",
             "Stickland Product"="gold",
             "*C. difficile* Growth Substrate"="darkorchid1",
             "*C. difficile* Metabolic Product"="gold",
             "Other"="grey"),
  
  GENE.PATHWAY=c("Amine and polyamine degradation"="olivedrab",
                 "Amino-acid biosynthesis"="deepskyblue3",
                 "Amino-acid degradation"="lightskyblue",
                 "Aromatic compound metabolism"="burlywood",
                 "Bacterial outer membrane biogenesis"="green",
                 "Carbohydrate acid metabolism"="purple4",
                 "Carbohydrate degradation"="darkorchid1",
                 "Carbohydrate metabolism"="plum2",
                 "Cofactor biosynthesis"="coral",
                 "Glycolipid biosynthesis"="gold",
                 "Metabolic intermediate biosynthesis"="chocolate3",
                 "Phospholipid metabolism"="yellow1",
                 "Porphyrin-containing compound metabolism"="grey20",
                 "Purine metabolism"="firebrick1",
                 "Pyrimidine metabolism"="red4",
                 "Sulfur metabolism"="lightgoldenrod",
                 "Other"="white"),
  
  Core=c("CA"="royalblue",
         "CDCA"="cadetblue1",
         "DCA"="firebrick",
         "LCA"="lightpink2",
         "aMCA"="orange",
         "bMCA"="darkorange3",
         "HCA"="springgreen4",
         "wMCA"="tan4",
         "HDCA"="gold",
         "UDCA"="grey"),
  
  BA=c("Primary Conjugated"="lightblue",
        "Primary Deconjugated"="darkblue",
        "Secondary Conjugated"="pink",
        "Secondary Deconjugated"="darkred"),
  
  speciesplot=c("Escherichia coli"="navy",
                "Klebsiella oxytoca"="deepskyblue",
                "Citrobacter freundii"="aquamarine",
                "Klebsiella pneumoniae"="cyan", 
                "Salmonella enterica"="royalblue",
                "Enterobacter cloacae"="skyblue",
                "Escherichia fergusonii"="cadetblue4",      
                "Citrobacter youngae"="cadetblue1",     
                "Salmonella bongori"="blue3",
                "Citrobacter portucalensis" ="turquoise",       
                "Proteus mirabilis"="lightcyan",     
                "Other"="grey"),
  
  familyplot=c("Enterobacteriaceae"="darkblue",
               "Yersiniaceae"="turquoise",
               "Vibrionaceae"="skyblue",
               "Pseudomonadaceae"="royalblue",
             "Lactobacillaceae"="red4",
             "Enterococcaceae"="firebrick2",
             "Erysipelotrichaceae"="tomato2",
             "Coprobacillaceae"="indianred",#
             "Turicibacteraceae"="orangered3",#
             "Streptococcaceae"="pink",
             "Lachnospiraceae"="goldenrod4",
             "Acutalibacteraceae"="gold3",
             "Ruminococcaceae"="gold1",
             "CAG-74"="yellow2",
             "UBA1381"="lemonchiffon",
             "Oscillospiraceae"="lightgoldenrod1",
             "Anaerovoracaceae"="khaki3",
             "Clostridiaceae"="yellow4",#
             "Eubacteriaceae"="goldenrod2",#
             "Peptostreptococcaceae"="darkgoldenrod",#
             "Monoglobaceae"="yellow3",
             "Butyricicoccaceae"="lightgoldenrod4",
             "Anaerotignaceae"="yellow",
             "Acidaminococcaceae"="sandybrown",
             "Veillonellaceae"="chocolate2",
             "Megasphaeraceae"="tan3",
             "Bacteroidaceae"="orchid",
             "Rikenellaceae"="purple",
             "Tannerellaceae"="magenta4",
             "Marinifilaceae"="violet",
             "Barnesiellaceae"="purple4",
             "Akkermansiaceae"="deepskyblue4",
             "Bifidobacteriaceae"="darkolivegreen4",
             "Coriobacteriaceae"="yellowgreen",
             "Eggerthellaceae"="lightgreen",
             "Actinomycetaceae"="green",
             "Burkholderiaceae"="cyan",
             "Synergistaceae"="whitesmoke",
             "Fusobacteriaceae"="papayawhip",
             "Dialisteraceae"="thistle1",
             "Desulfovibrionaceae"="lavender",
             "Methanobacteriaceae"="grey20",
             "Other"="grey"),
  
  
  phylumplot=c("Proteobacteria"="lightskyblue",
          "Firmicutes"="lightpink",
          "Firmicutes_A"="#F6FF8E",
          "Firmicutes_C"="#FCCD6E",
          "Bacteroidota"="#D3A6FF",
          "Actinobacteriota"="#BFFFA8",   
          "Fusobacteriota"="#DDFDFF",     
          "Methanobacteriota"="#EE90FF",
          "Synergistota"="#C1A5A5")
)
